### ISSUE TITLE
TConstruct issue

### ISSUE THREAD

**Issue by HFinner** [malte0811/IndustrialWires#67] opened 2019-01-13 23:23 UTC
**Issue description:** Crashing client when moving items from the player inventory to a tinker construct's Crafting station. I also have turned off the item display on top of the station.

(I am posting it on here because the TConstruct dev told me to ask you guys, since the issue apparently involves IW)

**If crashed, link to crash report (use a site such as pastebin):** https://pastebin.com/bki7kXUW

**Versions:**

**Minecraft:** 1.12.2
**Forge:** 14.23.5.2806
**Mantle:** 1.3.3.39
**Tinkers Construct:** 2.12.0.113
**Industrial Wires:** 1.7-34
**Can it be reproduced with just Tinkers Construct, or are other mods required to reproduce the bug?**
Crashing randomly when using the crafting station from Tinkers Construct. Industrial Wires is somehow in the mix of this even though I am not using anything IW related in the table.

**Comment by malte0811** [comment] 2019-01-14 06:23
Interesting. I'll look into it in the next couple of days.

**Comment by malte0811** [comment] 2019-01-14 19:19
Do you happen to remember which item (probably a block) you put into the crafting table when this happened? Because while I'm going to fix this in IW I'm pretty sure this is technically a bug in whatever mod adds the item you put into there (the model is returning `null` for `getParticleTexture`, which isn't marked as `@Nullable`).
As a temporary measure you could downgrade IW to build 33, this crash definitely won't happen on that build and from a quick glance at the changelog there shouldn't have been any changes that could cause issues when downgrading.

**Comment by LemADEC** [comment] 2019-01-14 21:20
Issue is reproduced in single player when trying to craft a hopper while ExtraUtilities2 is installed.
Placing the chest, then adding 1 iron ingot will freeze the output and crash eventually.
forge-1.12.2-14.23.5.2796.jar
extrautils2-1.12-1.9.8.jar
jei_1.12.2-4.14.4.254.jar
ImmersiveEngineering-0.12-88.jar
IndustrialWires-1.7-34.jar

**Comment by LemADEC** [comment] 2019-01-14 21:27
On a side note, I suggest to run some profiling on isValidTextureSource(). Scanning every component textures during recipe matching sounds a bit "intensive".

**Comment by malte0811** [comment] 2019-01-14 21:32
Yes, that's one thing I'm planning to change (I'll only check textures when the other ingredient of the recipe is present). Thanks for the tip about XU, I'll check whether they're doing anything strange.

**Comment by HFinner** [comment] 2019-01-14 22:07
The few times it crashed I was putting a normal chest inside of the station, then the other time it crashed I put a backpack from IronBackpacks into the station. I cannot say what the other players on my server were putting into their stations but it was also crashing them

**Comment by BSKCorp** [comment] 2019-01-15 04:09
This also happens with AE2 Crafting terminal. Not sure how to link my posted issue. But the crash log is exactly the same.

**Closed as completed** 2019-01-15 07:32 UTC
